[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"

[context.production.environment]
  NODE_ENV = "production"

[secrets_scanning]
  enabled = true
  omit_paths = ["dist/**", "node_modules/**", "server/public/**", "**/site_knowledge.json"]
  omit_keys = ["GROQ_MODEL", "FROM_EMAIL", "NOTIFY_EMAIL", "GSHEET_WEBAPP_URL", "SHEETS_TOKEN", "RESEND_API_KEY"]